# CI de Nível 01 - Disparo Manual através de clique

# nome da pipeline
name: "Execução Manual"

# gatilhos / triggers - regras de disparo
# gatilho manual = workflow_dispatch

on:
    workflow_dispatch:

#tarefas dentro da pipeline = jobs

jobs:
    #nome do job
    e2e-tests:
        # maquina onde o job vai rodar
        runs-on: ubuntu-latest

        # passos do job
        steps:
            # clone do projeto
            - uses: actions/checkout@v4

            # instalção do node
            - uses: actions/setup-node@v4
              with:
                  node-version: 24.x

            # instalação do Yarn
            - name: Instalando Yarn
              run: npm install -g yarn
            
            #   instalação das dependências
            - name: Instalando dependências
              run: yarn
            
            # instalação dos Browsers do Playwright
            - name: Instalando Browsers do Playwright
              run: yarn playwright install
            
            # executar os testes e2e
            - name: Executando testes e2e
              run: yarn run e2e

            - name: Upload relatório Playwright
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: playwright-report
                path: playwright-report/

            - name: Enviar email
              if: always()
              uses: dawidd6/action-send-mail@v3
              with:
                server_address: smtp.gmail.com
                server_port: 465
                secure: true

                username: ${{ secrets.EMAIL_USERNAME }}
                password: ${{ secrets.EMAIL_PASSWORD }}

                subject: |
                  Resultado dos testes - ${{ github.repository }}

                to: victorsoouto@gmail.com
                from: GitHub Actions

                html_body: |
                  <h2>Resultado da Execução</h2>

                  <p><b>Status:</b> ${{ job.status }}</p>
                  <p><b>Repositório:</b> ${{ github.repository }}</p>
                  <p><b>Branch:</b> ${{ github.ref_name }}</p>

                  <p>
                    <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">
                      Ver execução completa
                    </a>
                  </p>